apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: dns-firewall
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: ai-classifier:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/models/domain_classifier.pkl"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: dns-firewall
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ai-service